# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: postgresql
  encoding: utf8
  database: myapp_development
  username: myapp
  password: 123456

test:
  adapter: postgresql
  encoding: utf8
  database: myapp_test
  username: myapp
  password: 123456

# production:
  # adapter: mysql2
  # encoding: utf8
  # database: myapp_roduction
  # pool: 5
  # host: localhost
  # username: boleia
  # password: a1040955$
